#!/usr/bin/env bash
set -e

function show_usage {
  echo "USAGE: $0 [options]"
  echo "Options:"
  echo "    -h, --help: show this message and exit"
  echo "    -t, --test: test mode (don't install, push to github or delete this script)"
  }

for arg in "$@"
do
  case $arg in
      -t|--test)
        test_mode=Y
      ;;
      -h|--help)
        show_usage
        exit 0
      ;;
      *)
        show_usage
        exit 1
      ;;
  esac
done

# build docs
cd docs
make clean
make html
cd ..

# Prepare requirements.txt for ReadThedocs
requirements_rtd=requirements_rtd.txt
requirements=requirements.txt
requirements_doc=requirements_doc.txt

echo "# DO NOT EDIT THIS FILE" > $requirements_rtd
echo "# =====================" >> $requirements_rtd
echo "# IT IS AUTOMATICALLY GENERATED FROM $requirements AND $requirements_doc" >> $requirements_rtd
echo "# " >> $requirements_rtd
for src_file in $requirements $requirements_doc
do
  cat $src_file >> $requirements_rtd
done

if [ "$test_mode" != "Y" ]
then
  # Open docs in browser
  ./open_docs.sh
fi
